#docker-compose stop && docker-compose build && docker-compose up -d

symfony:
    build: docker/symfony
    volumes:
    - .:/var/www/symfony

    # I dont understand this
    tty: true 

db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: root
        MYSQL_PASSWORD: root

nginx:
    image: nginx
    links:
        - php-fpm

    # Change port if needed
    ports:
        - "80:80" 
    volumes_from:
        - symfony
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./logs/nginx/:/var/log/nginx

php-fpm:
    build: docker/php-fpm
    links:
        - db
    volumes_from:
        - symfony